t

diff --git a/validate-json-schema/action.yml b/validate-json-schema/action.yml
--- a/validate-json-schema/action.yml
+++ b/validate-json-schema/action.yml
@@ -43,7 +43,7 @@ runs:
 
     - run: |
         if [ "$RUNNER_OS" != "Linux" ]; then
-          echo "::error::wrong OS, please select runs-on: ubuntu-latest" && exit
+          echo "::error::wrong OS, please select runs-on: ubuntu-latest" && exit 1
           exit 95
         fi
       shell: bash
